import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/navBar";
import content from "@/statics/content";
import Section from "@/components/section";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
      <main>
        <div className={clsx(["flex px-8 py-12 text-primary items-start"])}>
          <div
            className={clsx([
              "content-container",
              "flex-4",
              "flex flex-col gap-12",
              "max-w-[calc(100vw-12rem)]",
            ])}
          >
            <Section id="overview" title="本书概况">
              <div>{content.overView.p1}</div>
              <div>{content.overView.p2}</div>
              <div>{content.overView.quote}</div>
              <div>{content.overView.p3}</div>
              <div>{content.overView.p4}</div>
            </Section>

            <Section id="author-translator" title="作者译者介绍">
              <div>{content.overView.p1}</div>
              <div>{content.overView.p2}</div>
              <div>{content.overView.quote}</div>
              <div>{content.overView.p3}</div>
              <div>{content.overView.p4}</div>
            </Section>

            <Section id="chapter-overview" title="章节梗概">
              <div>{content.overView.p1}</div>
              <div>{content.overView.p2}</div>
              <div>{content.overView.quote}</div>
              <div>{content.overView.p3}</div>
              <div>{content.overView.p4}</div>
            </Section>

            <Section id="recommendation" title="推荐语">
              <div>{content.overView.p1}</div>
              <div>{content.overView.p2}</div>
              <div>{content.overView.quote}</div>
              <div>{content.overView.p3}</div>
              <div>{content.overView.p4}</div>
            </Section>

            <Section id="origin-info" title="原著信息">
              <div>{content.overView.p1}</div>
              <div>{content.overView.p2}</div>
              <div>{content.overView.quote}</div>
              <div>{content.overView.p3}</div>
              <div>{content.overView.p4}</div>
            </Section>
          </div>
          <NavBar className="fixed top-0 right-0 flex-1 p-8 mt-20  max-h-[calc(100vh-14rem)] overflow-y-auto block self-start" />
        </div>
      </main>

      <div className="footer h-16"></div>
    </>
  );
}
